version: '3.8'

services:
  app:
    container_name: cdr_api
    image: cdr_api:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
    depends_on:
      sqlserver:
        condition: "service_started"
    ports:
     - "8080:80"

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    hostname: sqlserver
    volumes:
      - mssql_data:/var/opt/mssql
    environment:
      SA_PASSWORD: "Ig9379992"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"


volumes:
  mssql_data: {}   